// README.md — the very first file a guardian sees when they open the ZIP.
// Explains what each other file is, and (importantly) tells them the one-file
// drag-and-drop path into any consumer chatbot.
//
// Kept as a template function (not a static string) so counts / student names
// can be interpolated when we want, without forcing a rewrite here.

import type { FormatterManifest } from './types.js';

const encoder = new TextEncoder();

export interface ArchiveReadmeInput {
  manifest: FormatterManifest;
  schoolName?: string;
  studentNames?: string[];
  /** Which of the top-level files exist in this archive (drives the file list). */
  includes: {
    notes: boolean;
    messages: boolean;
    photos: boolean;
    viewer: boolean;
    dailyReports: boolean;
  };
  /** 'csv' | 'xlsx' | 'json' — which spreadsheet format was chosen. */
  format: 'csv' | 'xlsx' | 'json';
}

export function writeArchiveReadme(input: ArchiveReadmeInput): Uint8Array {
  const { manifest, schoolName, studentNames, includes, format } = input;
  const kids = (studentNames ?? []).filter(Boolean);
  const familyLabel = kids.length === 0
    ? 'your family'
    : kids.length === 1
      ? kids[0]!
      : kids.slice(0, -1).join(', ') + ' & ' + kids[kids.length - 1]!;
  const exportedDate = manifest.exportedAt.slice(0, 10);

  const p: string[] = [];
  p.push(`# ${familyLabel} — Brightwheel takeout`);
  p.push('');
  p.push(
    `Exported ${exportedDate}${schoolName ? ' from ' + schoolName : ''}. ` +
    `Contains ${manifest.counts.notes} notes, ${manifest.counts.messages} ` +
    `messages, and ${manifest.counts.photos} photos.`,
  );
  p.push('');
  p.push('## What is in this archive');
  p.push('');
  if (includes.viewer) {
    p.push('- **`viewer/index.html`** — open this in your browser for a searchable timeline + photo gallery. Works offline, no internet needed.');
  }
  p.push('- **`story.md`** — a chronological narrative of the archive. Drop into any AI chatbot to ask questions (see next section).');
  if (includes.photos) p.push('- **`photos/`** — every JPEG your child was tagged in, with the original capture date stamped into EXIF.');
  if (includes.notes) {
    p.push(format === 'xlsx'
      ? '- **Excel workbook** — notes, messages, and photo index on separate tabs.'
      : format === 'json'
        ? '- **`notes.json`, `messages.json`, `photos.json`** — machine-readable JSON envelopes.'
        : '- **`notes.csv`, `messages.csv`, `photos.csv`** — spreadsheet-friendly. Opens in Excel, Numbers, Google Sheets.');
  }
  if (includes.dailyReports) {
    p.push(format === 'json'
      ? '- **`daily-reports.json`** — daily reports (health checks, food, naps, potty, incidents).'
      : '- **`daily-reports.csv`** — daily reports (health checks, food, naps, potty, incidents).');
  }
  p.push('- **`manifest.json`** — machine-readable metadata (school, students, staff, counts).');
  p.push('- **`takeout.log`** — the diagnostic log of this export run. Useful if you file a bug.');
  p.push('');
  p.push('## Ask an AI about your archive');
  p.push('');
  p.push(
    'Drag **`story.md`** into ChatGPT, Claude, Gemini, Copilot, Perplexity, or ' +
    'NotebookLM — then ask things like:',
  );
  p.push('');
  p.push(`- *"Tell me about ${kids[0] ?? "my kid"}'s year."*`);
  p.push(`- *"Which teachers wrote the warmest notes?"*`);
  p.push(`- *"Summarize the month I was out sick."*`);
  p.push(`- *"When did we first hear about the field trip?"*`);
  p.push('');
  p.push(
    'For visual answers ("*which of these photos would make a good birthday ' +
    'card?*"), also drag a handful of files from `photos/` into the chat ' +
    'alongside `story.md`. Most chatbots cap image uploads at ~10–20 files ' +
    'per turn, so pick a small selection.',
  );
  p.push('');
  p.push('## Privacy');
  p.push('');
  p.push(
    'This archive contains photos, names, and messages of other children too — ' +
    'group photos, classroom messages, teacher notes about the class. Treat it ' +
    "like a family photo album: fine on your own computer or an encrypted " +
    'backup, but think before uploading the whole thing to a public cloud folder ' +
    'or sharing the ZIP outside your household.',
  );
  p.push('');
  p.push('---');
  p.push('');
  p.push('_Generated by Takeout for Brightwheel. Runs entirely in your browser._');
  p.push('_Not affiliated with Brightwheel, Inc. "Brightwheel" is a trademark of Brightwheel, Inc._');
  p.push('');

  return encoder.encode(p.join('\n'));
}
