// story.md — a chronological, human- and LLM-readable narrative of the
// archive. Sits alongside notes.csv / messages.csv / photos/ inside the
// export so a guardian can drop this single file into ChatGPT, Claude,
// Gemini, Copilot, Perplexity, or NotebookLM and ask questions about the
// year — no server, no login, no upload of the whole photo archive.
//
// See docs/AGENTIC-STRATEGY.md in the project repo for the "why this
// format" reasoning (short version: Markdown is the format all consumer
// chatbots ingest well and stays under every product's upload cap even
// for multi-year exports).

import type { NoteRow, MessageRow, PhotoRow, FormatterManifest } from './types.js';

const encoder = new TextEncoder();

export interface StoryInput {
  notes: NoteRow[];
  messages: MessageRow[];
  photos: PhotoRow[];
  manifest: FormatterManifest;
  /** Optional friendly context. Falls back to "your family" if unknown. */
  schoolName?: string;
  /** Display names of the children in the export, in roster order. */
  studentNames?: string[];
}

/**
 * Render the export as `story.md` bytes. Deterministic — same input yields
 * byte-identical output (tests rely on this).
 */
export function writeStoryMd(input: StoryInput): Uint8Array {
  const { notes, messages, photos, manifest, schoolName, studentNames } = input;

  const kids = (studentNames ?? []).filter(Boolean);
  const familyLabel = kids.length === 0
    ? 'your family'
    : kids.length === 1
      ? kids[0]!
      : kids.slice(0, -1).join(', ') + ' & ' + kids[kids.length - 1]!;

  const exportedDate = manifest.exportedAt.slice(0, 10);
  const dateRangeLine = formatDateRange(manifest.dateRange);

  const entries = collectEntries(notes, messages, photos);
  const monthGroups = groupByMonth(entries);

  const parts: string[] = [];
  parts.push(`# ${familyLabel} — Brightwheel archive`);
  parts.push('');
  if (schoolName) {
    parts.push(`Exported ${exportedDate} from ${schoolName}.`);
  } else {
    parts.push(`Exported ${exportedDate}.`);
  }
  if (dateRangeLine) parts.push(dateRangeLine);
  parts.push('');
  parts.push('## About this file');
  parts.push('');
  parts.push(
    'This is a chronological narrative of the notes, messages, and photos ' +
    "your child's school captured in Brightwheel. Photos are referenced by " +
    'their relative path inside this archive (e.g. `photos/…`).',
  );
  parts.push('');
  parts.push(
    'Drop this file into ChatGPT, Claude, Gemini, Copilot, Perplexity, or ' +
    'NotebookLM and ask questions like:',
  );
  parts.push('');
  parts.push(`- *"Tell me about ${kids[0] ?? "my kid"}'s year."*`);
  parts.push(`- *"Which teachers wrote the warmest notes?"*`);
  parts.push(`- *"What did we miss in the month I was out sick?"*`);
  parts.push('');
  parts.push(
    'The photo files themselves are not embedded in this document (that would ' +
    'break most chatbot upload limits). If your chatbot supports images and you ' +
    'want visual answers, additionally drag a handful of files from `photos/` ' +
    'into the chat alongside this file.',
  );
  parts.push('');
  parts.push(
    `**Counts:** ${manifest.counts.notes} notes · ${manifest.counts.messages} ` +
    `messages · ${manifest.counts.photos} photos.`,
  );
  parts.push('');
  parts.push('---');
  parts.push('');

  if (entries.length === 0) {
    parts.push('_No entries in this export._');
    parts.push('');
  } else {
    for (const { monthKey, monthLabel, monthEntries } of monthGroups) {
      parts.push(`## ${monthLabel}`);
      parts.push('');
      void monthKey; // reserved for future per-month anchors
      for (const entry of monthEntries) {
        parts.push(renderEntry(entry));
        parts.push('');
      }
    }
  }

  parts.push('---');
  parts.push('');
  parts.push(
    '_Generated by Takeout for Brightwheel. Not affiliated with Brightwheel, Inc._',
  );
  parts.push('');

  return encoder.encode(parts.join('\n'));
}

// ---- Internal helpers ------------------------------------------------------

type EntryKind = 'note' | 'message' | 'photo';

interface Entry {
  kind: EntryKind;
  date: string; // ISO YYYY-MM-DD
  time: string; // HH:MM (may be empty)
  who: string;
  body: string;
  mediaFiles: string[];
  studentName?: string;
}

function collectEntries(
  notes: NoteRow[],
  messages: MessageRow[],
  photos: PhotoRow[],
): Entry[] {
  const out: Entry[] = [];
  for (const n of notes) {
    out.push({
      kind: 'note',
      date: n.date,
      time: n.time,
      who: n.author || 'teacher',
      body: n.body,
      mediaFiles: n.mediaFiles ?? [],
      studentName: n.studentName,
    });
  }
  for (const m of messages) {
    out.push({
      kind: 'message',
      date: m.date,
      time: m.time,
      who: m.sender || 'unknown sender',
      body: m.body,
      mediaFiles: m.mediaFiles ?? [],
    });
  }
  // Only surface standalone photos (no attachedNote) — otherwise the photo
  // already rides along with its parent note, and we'd double-emit.
  for (const p of photos) {
    if (p.attachedNote && p.attachedNote.trim() !== '') continue;
    out.push({
      kind: 'photo',
      date: p.date,
      time: p.time,
      who: p.author || 'teacher',
      body: '',
      mediaFiles: [p.filename],
      studentName: p.studentName,
    });
  }
  out.sort((a, b) => {
    if (a.date !== b.date) return a.date < b.date ? -1 : 1;
    if (a.time !== b.time) return a.time < b.time ? -1 : 1;
    // Stable-ish tiebreak: notes before messages before photos.
    return kindOrder(a.kind) - kindOrder(b.kind);
  });
  return out;
}

function kindOrder(k: EntryKind): number {
  return k === 'note' ? 0 : k === 'message' ? 1 : 2;
}

function groupByMonth(
  entries: Entry[],
): Array<{ monthKey: string; monthLabel: string; monthEntries: Entry[] }> {
  const groups = new Map<string, Entry[]>();
  for (const e of entries) {
    const key = e.date.slice(0, 7); // YYYY-MM
    const bucket = groups.get(key);
    if (bucket) bucket.push(e);
    else groups.set(key, [e]);
  }
  const monthKeys = [...groups.keys()].sort();
  return monthKeys.map((monthKey) => ({
    monthKey,
    monthLabel: formatMonthLabel(monthKey),
    monthEntries: groups.get(monthKey)!,
  }));
}

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

function formatMonthLabel(monthKey: string): string {
  const [yearStr, monthStr] = monthKey.split('-');
  const year = Number(yearStr);
  const monthIdx = Number(monthStr) - 1;
  if (!Number.isFinite(year) || monthIdx < 0 || monthIdx > 11) {
    return monthKey;
  }
  return `${MONTH_NAMES[monthIdx]} ${year}`;
}

function renderEntry(e: Entry): string {
  const headerBits = [e.date];
  if (e.time) headerBits.push(e.time);
  headerBits.push(`${e.kind} from ${e.who}`);
  if (e.studentName) headerBits.push(`about ${e.studentName}`);
  const header = `### ${headerBits.join(' · ')}`;

  const lines = [header];
  if (e.body && e.body.trim() !== '') {
    lines.push('');
    lines.push(escapeBodyForMarkdown(e.body));
  }
  if (e.mediaFiles.length > 0) {
    lines.push('');
    lines.push(`Photos: ${e.mediaFiles.join(', ')}`);
  }
  return lines.join('\n');
}

/**
 * Very light markdown-safe rendering: preserve line breaks the author wrote,
 * escape a leading `#` that would look like a stray header, and leave
 * everything else as-is (Brightwheel note/message bodies are prose, not
 * markdown — no need for defensive escaping beyond preventing accidental
 * heading promotion).
 */
function escapeBodyForMarkdown(body: string): string {
  return body
    .split(/\r?\n/)
    .map((line) => (line.startsWith('#') ? '\\' + line : line))
    .join('\n');
}

function formatDateRange(range: FormatterManifest['dateRange']): string {
  if (!range) return '';
  const { from, to } = range;
  if (!from && !to) return '';
  if (from && to) return `Covering ${from} to ${to}.`;
  if (from) return `Covering ${from} to today.`;
  return `Covering everything up to ${to}.`;
}
